# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c0a4f57c6f2803211055e011288accb6"
application_url = "https://boltrapp.pryxotech.com"
embedded = true

name = "Boltr Bulk Price Editor"
handle = "bulk-price-editor-boltr"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "https://boltrapp.pryxotech.com/webhooks"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "https://boltrapp.pryxotech.com/webhooks"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "https://boltrapp.pryxotech.com/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory,write_inventory,read_themes,write_themes,write_orders,read_orders,read_customers,write_customers,write_markets,read_markets"

[auth]
redirect_urls = [
  "https://boltrapp.pryxotech.com/auth/callback",
  "https://boltrapp.pryxotech.com/shopify/callback",
  "https://boltrapp.pryxotech.com/api/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
